-- MySQL Script generated by MySQL Workbench
-- 08/30/15 13:14:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema health_it2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema health_it2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `health_it2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `health_it2` ;

-- -----------------------------------------------------
-- Table `health_it2`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_it2`.`persons` (
  `person_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `person_first_name` VARCHAR(45) NULL COMMENT '',
  `person_last_name` VARCHAR(45) NULL COMMENT '',
  `person_age` INT NULL COMMENT '',
  `person_birth_date` DATETIME NULL COMMENT '',
  `person_citizenID` VARCHAR(45) NULL COMMENT '',
  `person_house_num` VARCHAR(45) NULL COMMENT '',
  `person_soi` VARCHAR(45) NULL COMMENT '',
  `person_road` VARCHAR(45) NULL COMMENT '',
  `person_tumbon` VARCHAR(45) NULL COMMENT '',
  `person_amphur` VARCHAR(45) NULL COMMENT '',
  `person_province` VARCHAR(45) NULL COMMENT '',
  `person_post_code` INT NULL COMMENT '',
  `person_mobile_phone` VARCHAR(45) NULL COMMENT '',
  `person_phone` VARCHAR(45) NULL COMMENT '',
  `person_sex` VARCHAR(45) NULL COMMENT '',
  `person_mooh_num` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`person_id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = 'Keep person records';


-- -----------------------------------------------------
-- Table `health_it2`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_it2`.`questions` (
  `question_id` INT NOT NULL COMMENT '',
  `disease_types` VARCHAR(45) NULL COMMENT '',
  `question_date` DATE NULL COMMENT '',
  PRIMARY KEY (`question_id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = 'Super class of question; when new form has been created ,it has to inherit from this table for dynamic questions.';


-- -----------------------------------------------------
-- Table `health_it2`.`question_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_it2`.`question_1` (
  `symptom_1_1` VARCHAR(45) NULL COMMENT '',
  `symptom_1_2` VARCHAR(45) NULL COMMENT '',
  `symptom_1_3` VARCHAR(45) NULL COMMENT '',
  `symptom_2` VARCHAR(45) NULL COMMENT '',
  `symptom_3` VARCHAR(45) NULL COMMENT '',
  `symptom_4_1` VARCHAR(45) NULL COMMENT '',
  `symptom_4_2` VARCHAR(45) NULL COMMENT '',
  `symptom_4_3` VARCHAR(45) NULL COMMENT '',
  `symptom_4_4` VARCHAR(45) NULL COMMENT '',
  `symptom_5` VARCHAR(45) NULL COMMENT '',
  `symptom_5_date` DATE NULL COMMENT '',
  `symptom_5_result` VARCHAR(100) NULL COMMENT '',
  `symptom_6` VARCHAR(45) NULL COMMENT '',
  `symptom_6_date` DATE NULL COMMENT '',
  `symptom_6_result` VARCHAR(100) NULL COMMENT '',
  `symptom_7_1` VARCHAR(45) NULL COMMENT '',
  `symptom_7_1_result` VARCHAR(45) NULL COMMENT '',
  `symptom_7_2` VARCHAR(45) NULL COMMENT '',
  `symptom_7_2_result` VARCHAR(45) NULL COMMENT '',
  `symptom_7_3` VARCHAR(45) NULL COMMENT '',
  `symptom_7_3_result` VARCHAR(45) NULL COMMENT '',
  `symptom_8` VARCHAR(45) NULL COMMENT '',
  `symptom_9_male` INT NULL COMMENT '',
  `symptom_9_female` INT NULL COMMENT '',
  `symptom_10_2_female` INT NULL COMMENT '',
  `symptom_10_2_male` INT NULL COMMENT '',
  `symptom_10_1` VARCHAR(45) NULL COMMENT '',
  `symptom_10_1_male` VARCHAR(45) NULL COMMENT '',
  `questions_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`questions_id`)  COMMENT '',
  CONSTRAINT `fk_question_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `health_it2`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'Inherit from questions table ';


-- -----------------------------------------------------
-- Table `health_it2`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_it2`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `role_description` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = 'eg Father , Son ,Husban , Wife';


-- -----------------------------------------------------
-- Table `health_it2`.`relationship_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_it2`.`relationship_type` (
  `relationship_type_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `relationship_type_description` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`relationship_type_id`)  COMMENT '')
ENGINE = InnoDB
COMMENT = 'eg  Parent ,Child , Married';


-- -----------------------------------------------------
-- Table `health_it2`.`relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_it2`.`relationship` (
  `relationship_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `person_1_id` INT NOT NULL COMMENT '',
  `role_1_id` INT NOT NULL COMMENT '',
  `relationship_type_id` INT NOT NULL COMMENT '',
  `person_2_id` INT NOT NULL COMMENT '',
  `role_2_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`relationship_id`)  COMMENT '',
  INDEX `fk_relationships_person1_idx` (`person_1_id` ASC)  COMMENT '',
  INDEX `fk_relationships_roles1_idx` (`role_1_id` ASC)  COMMENT '',
  INDEX `fk_relationships_relationship_type1_idx` (`relationship_type_id` ASC)  COMMENT '',
  INDEX `fk_relationship_persons1_idx` (`person_2_id` ASC)  COMMENT '',
  INDEX `fk_relationship_roles1_idx` (`role_2_id` ASC)  COMMENT '',
  CONSTRAINT `fk_relationships_person1`
    FOREIGN KEY (`person_1_id`)
    REFERENCES `health_it2`.`persons` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relationships_roles1`
    FOREIGN KEY (`role_1_id`)
    REFERENCES `health_it2`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relationships_relationship_type1`
    FOREIGN KEY (`relationship_type_id`)
    REFERENCES `health_it2`.`relationship_type` (`relationship_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relationship_persons1`
    FOREIGN KEY (`person_2_id`)
    REFERENCES `health_it2`.`persons` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relationship_roles1`
    FOREIGN KEY (`role_2_id`)
    REFERENCES `health_it2`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'The relationship uses to identify role and relationship  between two people';


-- -----------------------------------------------------
-- Table `health_it2`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_it2`.`doctors` (
  `doctor_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `doctor_name` VARCHAR(45) NULL COMMENT '',
  `doctor_mobile_phone` VARCHAR(45) NULL COMMENT '',
  `doctor_phone` VARCHAR(45) NULL COMMENT '',
  `hospital` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`doctor_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `health_it2`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_it2`.`patients` (
  `patient_id` INT NOT NULL COMMENT '',
  `doctor_id` INT NOT NULL COMMENT '',
  `registration_date` DATE NULL COMMENT '',
  `person_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`patient_id`)  COMMENT '',
  INDEX `fk_patients_doctors1_idx` (`doctor_id` ASC)  COMMENT '',
  INDEX `fk_patients_persons1_idx` (`person_id` ASC)  COMMENT '',
  CONSTRAINT `fk_patients_doctors1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `health_it2`.`doctors` (`doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patients_persons1`
    FOREIGN KEY (`person_id`)
    REFERENCES `health_it2`.`persons` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = ' patient table  associates with person and doctor';


-- -----------------------------------------------------
-- Table `health_it2`.`patients_do_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_it2`.`patients_do_questions` (
  `patients_do_questions_id` INT NOT NULL COMMENT '',
  `question_id` INT NOT NULL COMMENT '',
  `registration_date` DATE NULL COMMENT '',
  `patient_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`patients_do_questions_id`)  COMMENT '',
  INDEX `fk_patients_do_questions_questions1_idx` (`question_id` ASC)  COMMENT '',
  INDEX `fk_patients_do_questions_patients1_idx` (`patient_id` ASC)  COMMENT '',
  CONSTRAINT `fk_patients_do_questions_questions1`
    FOREIGN KEY (`question_id`)
    REFERENCES `health_it2`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patients_do_questions_patients1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `health_it2`.`patients` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
